/*
 * Mise en place d’un langage graphique pour l’éditeur SEPIA
 * MIF20 - PRIM - TER || Janvier - Février 2015
 * Université Lyon 1 || Département Informatique
 */

package main;

import myComponent.MyTable;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.BoxLayout;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import rules.Rule;
import tools.transferTools.MyTransferHandlerTable;

/**
 *
 * @author Le Duc Tan NGUYEN
 */
public class InterfaceJFrame extends javax.swing.JFrame {

    private ArrayList<Rule> listRules;
    private Model model;
        
    
    /**
     * Creates new form Main
     *
     * @param nameFrame : nom du programme principal
     */
    public InterfaceJFrame(Model model, String nameFrame) {
        super(nameFrame);
        initComponents();
        // Incorporer la table dans un JScrollPane
        MyTable tab = new MyTable();
        if (tab.getColumnModel().getColumnCount() > 0) {
            tab.getColumnModel().getColumn(0).setMinWidth(50);
            tab.getColumnModel().getColumn(0).setPreferredWidth(80);
            tab.getColumnModel().getColumn(1).setMinWidth(150);
            tab.getColumnModel().getColumn(1).setPreferredWidth(200);
            tab.getColumnModel().getColumn(2).setMinWidth(150);
            tab.getColumnModel().getColumn(2).setPreferredWidth(200);
        }
        // Définir Gestion de Glisser-Déposer pour la table
        tab.setTransferHandler(new MyTransferHandlerTable());
        tab.setPreferredScrollableViewportSize(new Dimension(600, 100));
        
        JScrollPane jspTable = new javax.swing.JScrollPane();
        jspTable.setViewportView(tab);

        // Incorporer le canvas dans un JScrollPane
        View canvas = model.getView();
        canvas.setPreferredSize(new Dimension(550, 250));
        
        JScrollPane jspPnlCanvas = new JScrollPane();
        jspPnlCanvas.setViewportView(canvas);

        // Panel InterfaceJFrame
        JPanel pnlMain = new JPanel();
        pnlMain.setLayout(new BoxLayout(pnlMain, BoxLayout.PAGE_AXIS));
        pnlMain.setPreferredSize(new Dimension(700, 500));
        pnlMain.setMinimumSize(new Dimension(400, 200));

        // ajouter les autres composants au Panel InterfaceJFrame
        pnlMain.add(jspTable);
        pnlMain.add(jspPnlCanvas);

        // Incorporer les composants dans JFrame
        pnlMain.setOpaque(true);
        this.setContentPane(pnlMain);
        this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
